---
title: "G7 Countries Electricity Source"
author: '@spectrumsing'
date: '2022-07-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(stringr)
library(ggplot2)
library(bbplot)
```

## Load Data
```{r}
technology <- 
  read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-19/technology.csv')
```

## Data preperation
```{r, message=FALSE, warning=FALSE}
elec_from <- unique(G7_elec$variable)
fossil <- elec_from[c(1, 3, 6)]
renewable <- elec_from[c(4, 7, 8, 9)]
nuclear <- elec_from[5]

G7_elec <-
  technology %>% filter(str_detect(label, "Electricity from"), 
                        iso3c %in% c("USA", "JPN", "DEU", "FRA", "GBR", "ITA", "CAN")) %>% 
  mutate(variable, source = if_else(variable %in% fossil, "fossil", 
                                    if_else(variable %in% renewable, "renewable", 
                                            "nuclear"))) %>% 
  group_by(iso3c, year, source) %>% 
  mutate(prop = value/sum(value)) %>% 
  summarize(source_twh = sum(value)) %>% 
  group_by(iso3c, year) %>% 
  mutate(year_twh = sum(source_twh), 
         prop = source_twh/year_twh)
```

## Plot
```{r, warning=FALSE, message=FALSE, fig.width=14, fig.height=8.5}
windowsFonts(title = windowsFont("Inter Semi Bold"), 
             subtitle = windowsFont("Inter Medium"),
             subplot = windowsFont("Inter"),
             axis = windowsFont("Source Sans Pro"))


ggplot(G7_elec, 
       aes(x = year, 
           y = prop*100, 
           colour = source)) +
  geom_line(aes(color = source), 
            size = 1.2) +
  facet_wrap(~ iso3c, 
             nrow = 2, 
             scales = "free_x",
             labeller = as_labeller(c(CAN = "Canada",
                                      DEU = "Germany",
                                      FRA = "France",
                                      GBR = "United Kingdom",
                                      ITA = "Italy",
                                      JPN = "Japan",
                                      USA = "United States"))) +
  geom_hline(yintercept = 0, 
             size = 0.5, 
             colour="#333333") +
  xlim(c(1985, 2023)) +
  geom_label(data = G7_elec %>% 
               filter(year == 2020, 
                      source == "fossil") %>% 
               select(prop), 
             aes(x = 2023, 
                 y = prop*100, 
                 label = paste0(round(prop*100), "%")),
             label.size = NA,
             size = 3.75, 
             fill = NA,
             color = "#d7620a") +
  geom_label(data = G7_elec %>% 
               filter(year == 2020, 
                      source == "nuclear") %>% 
               select(prop), 
             aes(x = 2023, 
                 y = prop*100, 
                 label = paste0(round(prop*100), "%")),
             label.size = NA,
             size = 3.75, 
             fill = NA,
             color = "#666666") +
  geom_label(data = G7_elec %>% 
               filter(year == 2020, 
                      source == "renewable") %>% 
               select(prop), 
             aes(x = 2023, 
                 y = prop*100 + 1, 
                 label = paste0(round(prop*100), "%")),
             label.size = NA,
             size = 3.75,
             fill = NA,
             color = "#1c9e77") +
  scale_colour_manual(values = c("#d7620a", "#666666", "#1c9e77")) +
  labs(title = "G7 Countries Source of Electricity", 
       subtitle = "% of total production, 1985-2020",
       caption = "Source: data.nber.org") +
  bbc_style() +
  scale_colour_manual(values = c("#d7620a", "#666666", "#1c9e77")) +
  theme(plot.margin = margin(10, 30, 5, 30),
        plot.title = element_text(family = "title",
                                  size = 24),
        plot.subtitle = element_text(family = "subtitle",
                                     size = 16, 
                                     margin = margin(b = 25),
                                     colour = "#666666"),
        plot.caption = element_text(family = "axis",
                                    size = 11, 
                                    margin = margin(t = 15, b = 5), 
                                    colour = "#666666", 
                                    hjust = 0.5),
        panel.spacing.x = unit(1, "cm"),
        panel.spacing.y = unit(2, "cm"),
        axis.title = element_blank(),
        axis.text = element_text(family = "axis",
                                 size = 11),
        axis.text.x = element_text(margin = margin(t = -5)),
        strip.text.x = element_text(family = "subplot",
                                    size = 14),
        legend.position = c(0.95, 0.15),
        legend.justification = c(1, 0),
        legend.text = element_text(family = "subplot",
                                   size = 13))

ggsave("G7 Electricity Source.png", width = 16, height = 9)
```
